name: Test

on:
  push:

jobs:
  main:
    name: Many Tests
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Install Dependencies (Yarn)
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Document Generation Test
        run: yarn docs
